{% set name = "itmlogic" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa65eb9bff2a0ff3798bc10d6962874aa594d4ed9826d4a36c23cb3b81115e51

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - setuptools_scm

test:
  requires:
    - python {{ python_min }}
  imports:
    - itmlogic

about:
  home: https://github.com/edwardoughton/itmlogic
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Longley-Rice irregular terrain propagation model"
  doc_url: https://pypi.org/project/itmlogic/#description
  dev_url: https://github.com/edwardoughton/itmlogic

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - winstonjhoyle
    - Tata17
